name: ml101
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - pytorch
  - scikit-learn
  - torchmetrics
  - jupyter
  - pandas
  - plotly
  - tensorboard
  - matplotlib